version: 0.0.10.{build}
branches:
  only:
    - master
configuration: Release
before_build:
  - cmd: nuget restore
build:
  verbosity: normal
artifacts:
  - path: MmiSoft.Core\bin\$(configuration)\*.nupkg
assembly_info:
  patch: true
  file: '**\VersionInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
